server:
  port: 8989
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jsonPlaceholder-service
          uri: lb://jsonPlaceholder-service
          predicates:
            - Path=/jsonPlaceholder/**

        - id: websocket-service
          uri: lb:ws://websocket-service
          predicates:
            - Path=/ws/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: Sec-WebSocket-Protocol
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true