server:
  port: 8989
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**
eureka:
 routes:client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true