server:
  port: 8989
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: apis
          uri: http://localhost:8080
          predicates:
            - Path=/huy/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true