server:
  port: 8989
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jsonPlaceholder-service.yaml
          uri: lb://jsonPlaceholder-service.yaml
          predicates:
            - Path=/jsonPlaceholder/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true